#!/usr/bin/env python 3
#-*- coding:utf-8 -*-

'使用__slots__'

__author__='Liu Shanshan'

from types import MethodType
def set_age(self,age):
	self.age=age

class Student(object):
	pass

s=Student()
# s.set=MethodType(set_age,s)
# s.set(25)
# print(s.age)
s.set=set_age(s,25)
print(s.age)
