#!/usr/bin/env python3
#-*- coding:utf-8 -*-

'a class 和 instance'

__author__='Liu Shanshan'

# 第一种情况
class Student(object):
	def __init__(self,name,score):
		self.name=name
		self.score=score
art=Student('Liu Shanshan',99)
print(art.name)
print(art.score)

# 第二种情况
class Student(object):
	"""docstring for Student"""
	def __init__(self, name,score):
		self.name=name
		self.score=score
	def print_score(self):
		print('%s:%s'%(self.name,self.score))
bart=Student('Liu Shanshan',99)
bart.print_score()		
		
# 第三种情况
class Student(object):
	def __init__(self,score):
		self.score=score
	def get_grade(self):
		if self.score>=90:
			return 'A'
		elif self.score>=60:
			return 'B'
		else:
			return 'C'
lisa=Student(90)
bart=Student(59)
print(lisa.get_grade())
print(bart.get_grade())
